name=DevLab_Button
version=1.0.0
author=UNIT Electronics MX
maintainer=Adrian Rabadan, Cesar Bautista, Jonathan Mejorado, Fernando Flores
sentence=Arduino library for the I2C push-button module using the DevLab Device Protocol (DDP).
paragraph=DevLab Button library to read a debounced push button through DDP over I2C (Device ID 0x0110).
category=Sensors
url=https://github.com/UNIT-Electronics-MX/unit_devlab_button_library
architectures=*
includes=DevLab_Button.h
depends=DevLabDDP, DevLab_Interface
